application:
  port: 8000
database:
  host: "10.0.50.119"
  port: 5432
  username: "postgres"
  password: "525819Flash%"
  database_name: "rust-mail"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
